language: node_js

node_js:
  - 10

branches:
  only:
    - master
    - beta
    - production

cache: yarn

install:
  - yarn install

before_script:
  - yarn copy-monaco

matrix:
  include:
    - name: "Editor Pipeline"
      env:
        - PACKAGE_LOCATION=packages/editor
        - PACKAGE_NAME=editor
        - SITE_NAME=script-lab-react

    - name: "Server Pipeline"
      env:
        - PACKAGE_LOCATION=packages/server
        - PACKAGE_NAME=server
        - SITE_NAME=script-lab-react-server

script:
  - cd $PACKAGE_LOCATION
  - yarn lint || travis_terminate 1
  - yarn test || travis_terminate 1
  - yarn build || travis_terminate 1
  - cd $TRAVIS_BUILD_DIR
  - if [[ "$TRAVIS_PULL_REQUEST" == false ]]; then yarn deploy; fi

env:
  global:
    - HTTPS=true
    - secure: HexcEzdxAUC8YRm/qckg678+VYwbgn1yNdgtCtGDHX3ojgoQBQuMVMLFgflQE7YgaiZLU/4srND+IEDeLsVUjRTsI2uKPjxQup46sXiiTbo3r3Asc1Y99O8DsmnXwHKn9O2MZRfUwO5FpsMoq7ERrvrVC/uk5U4+CsPMapz633fHq6/NzdCMYG9J5BI+NuirxJPXOkw1rb+22hsCBGiGeYCEaEmgZppSy5IXLJU4YMLauqEQrq8KZEYaecObpqlA762oGG273WW0PdOMra1clkZMfScP6Z5S3A7K4Q7lDw1t5JOASX7Ongy4x46pqchr7hwGrAazWX7HziLQXcrjjAHzh0Le/yS1QfnRRlxc9fhTAhx14cA0oKrWvLXMAVk8uWPDprOIKHnmNKtCFWpcM6w6Ks9+1Ij7AP+BWt7whFuy8Ta2IPUDLsLAjaMZe9JOwpCGWZSseHpnoMTxLwfCv+yyP/6KdqR346NttCXW60jAb0a5bZQ41UEAi56f7Mxy7ffY8//25tx59jbwBZxgdHxvy5BWOQQ8bcNzGiorxQOxArwyBFEroi+6X0jt3APxjMpWSqQlxn7OncvEeBXDbDiaYhGPJctqfX8cW2QBjKpyfAx0axxbslivVW0ENLaasdc0Pd6IiTIqmiHq93yVIFq8BpJooEtaEzAlkHhc7xc=
    - secure: SiUgnxWC6yqYbgkPMyNnfo94maLXw9FfIKg6Qkj1qxjME2AnwAOSYyI2TXBtLoeHza31ZPFh8CPKeacvoUyiPhfOaufZMG0K6bV5tKFgHsl3OagYV+aui26Vuu/uTo9FBt9tVmHTmdMl5FlXV6UleqtQpjOTGZXOGOIVYbVGMk0G2+p0FkMDU6fadJVXloc8a7izg7rrpbMng5VTGqg3M/qZ8chul3li55Z6LUpYUzN13Pc2uIkAtWGt+W5ZF62xytScudklWkQRsFIAr7pOP253/x7th71jAT0Th8ijpdQGmoXev23phLG1oI5ba1pkBqljxsFeK8MYvDNeBFtE6att0B2x+irOXMlbxaZIXWU3/isAOHVQH5No1+Irmp8vq2gajtaVCAurU4WNGgsAiKrZ7gxqzq3FOpcshRgFlIVkDuoHboAMEYjR/IsGdZPuvFFNWK77YZ3678wUOk8+SxAdJdPa6YI/qaF4hH1O4r6LaW6uu4p+2dN3nJvDt27ZYurccsqFlkZc1FVAyAOJgy8wgaNrYrEHN2mmrxu2qvZh0ZTuNQei+XII9GBqwcSNfKiIfiLezC8lD8U1ekNPFrBGyPcKZQN5R0kLhS4w4Q2ozEEK5hdu8BHz0MTfxlcyeOmvtl0nu9Pdv9PEuTSxTi2owDrXYm+xUFNhc6FK40k=
